In [34]:
import tools
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
ser = tools.interface.open_serial_port()

In [ ]:
counts = np.zeros(10)
bins = np.linspace(0, 20000, 11)
for i in range(1000):
    data = tools.interface.read_serial_port(ser) * 0.001
    hist, bins = np.histogram(data, bins=bins)
    counts = counts + hist
    if i % 50 == 0:
        plt.bar(bins[:-1], counts, width=1000)
        plt.show()

In [7]:
ser = tools.interface.open_serial_port()
tools.interface.write_port_data_to_csv(ser, 'test.csv')

KeyboardInterrupt: 

In [115]:
import multiprocessing
import time

def count(ser, shared_list):
    signal = ser.read(1)
    signal += ser.read(ser.inWaiting())
    while True:
        data = tools.interface.read_serial_port(ser)
        shared_list += data[data<=10].tolist()

def g(shared_list):
    while True:
        time.sleep(1)
        if len(shared_list) > 0:
            mean = np.array(shared_list).mean()
        else:
            mean = 0
        print(mean)

manager = multiprocessing.Manager()
shared_list = manager.list()
serial = tools.interface.open_serial_port()
p1 = multiprocessing.Process(name="Read serial", target=count, args=[serial, shared_list])
p2 = multiprocessing.Process(name="Read serial", target=g, args=[shared_list])
p1.start()
p2.start()
p1.join()
p2.join()

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
1.875
4.954166666666667
4.954166666666667
4.954166666666667
4.954166666666667
4.954166666666667
4.954166666666667
4.954166666666667
4.954166666666667
4.954166666666667
4.954166666666667
4.954166666666667
4.954166666666667
4.9541

Process Read serial:
Process Read serial:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/karlo/miniconda3/envs/Mulan/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/karlo/miniconda3/envs/Mulan/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/karlo/miniconda3/envs/Mulan/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/tmp/ipykernel_4056/855872326.py", line 13, in g
    time.sleep(1)
  File "/home/karlo/miniconda3/envs/Mulan/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_4056/855872326.py", line 8, in count
    data = tools.interface.read_serial_port(ser)
KeyboardInterrupt
  File "/mnt/storage/Projects/Mulan/tools/interface.py", line 34, in read_serial_port
    signal = ser.read(1)
  File "/home/karlo/minicon

KeyboardInterrupt: 

In [97]:
data = tools.interface.read_serial_port(ser)

In [98]:
data

array([12383.75  , 11772.0625, 89058.075 , 28725.4125, 17833.225 ,
       13074.5875, 35037.95  ,  3862.8875])

In [105]:
data[np.logical_and(data>10000, data<20000)]

array([12383.75  , 11772.0625, 17833.225 , 13074.5875])

In [104]:
np.logical_and(data>10000, data<20000)

array([ True,  True, False, False,  True,  True, False, False])